[package]
name = "lotusd"
version.workspace = true
rust-version.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
blake3.workspace = true
cbor2.workspace = true
clap.workspace = true
clap_complete.workspace = true
data-encoding.workspace = true
dirs.workspace = true
ed25519-zebra.workspace = true
iroh.workspace = true
nutype.workspace = true
rand.workspace = true
serde.workspace = true
thiserror.workspace = true
thunderdome.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

# Our crates
lotusd-rpc.workspace = true
render = { workspace = true, features = ["clap"] }
state.workspace = true
storage.workspace = true
sync.workspace = true
version.workspace = true
wire.workspace = true

[dev-dependencies]
chrono.workspace = true
# In-memory iroh transport for multi-node tests.
iroh = { workspace = true, features = ["test-utils", "unstable-custom-transports"] }
tempfile.workspace = true
