[package]
name = "storage"
version.workspace = true
rust-version.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["sqlite"]
sqlite = ["dep:rand", "dep:rusqlite", "dep:thiserror"]

[dependencies]
chrono.workspace = true
rand = { workspace = true, optional = true }
rusqlite = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
wire.workspace = true

[dev-dependencies]
tempfile.workspace = true
